physical_ai_manager:
  ros__parameters:
    ai_worker:
      camera_topic_list: 
        - "cam_head:/zed/zed_node/left/image_rect_color/compressed"
        - "cam_wrist_left:/camera/cam_wrist_left/color/image_rect_raw/compressed"
        - "cam_wrist_right:/camera/cam_wrist_right/color/image_rect_raw/compressed"

      joint_sub_topic_list:
        - "follower_state:/joint_states"
        - "leader_left:/leader/left_arm_with_timestamp"
        - "leader_right:/leader/right_arm_with_timestamp"

      joint_pub_topic_list:
        - "leader_left:/leader/joint_trajectory_command_broadcaster_right/joint_trajectory"
        - "leader_right:/leader/joint_trajectory_command_broadcaster_left/joint_trajectory"

      observation_list:
        - "cam_head"
        - "cam_wrist_left"
        - "cam_wrist_right"
        - "state"

      action_list:
        - "action"

      joint_list:
        - "follower"
        - "leader_left"
        - "leader_right"

      inference_joint_order:
        follower:
          - arm_r_joint1
          - arm_r_joint2
          - arm_r_joint3
          - arm_r_joint4
          - arm_r_joint5
          - arm_r_joint6
          - arm_r_joint7
          - r_rh_r1_joint
          - arm_l_joint1
          - arm_l_joint2
          - arm_l_joint3
          - arm_l_joint4
          - arm_l_joint5
          - arm_l_joint6
          - arm_l_joint7
          - l_rh_r1_joint
        leader_left:
          - arm_l_joint1
          - arm_l_joint2
          - arm_l_joint3
          - arm_l_joint4
          - arm_l_joint6
          - arm_l_joint7
          - arm_l_joint5
          - l_rh_r1_joint
        leader_right:
          - arm_r_joint1
          - arm_r_joint4
          - arm_r_joint5
          - arm_r_joint6
          - arm_r_joint2
          - arm_r_joint3
          - arm_r_joint7
          - r_rh_r1_joint

      collect_joint_order:
        follower:
          - arm_r_joint1
          - arm_r_joint2
          - arm_r_joint3
          - arm_r_joint4
          - arm_r_joint5
          - arm_r_joint6
          - arm_r_joint7
          - r_rh_r1_joint
          - arm_l_joint1
          - arm_l_joint2
          - arm_l_joint3
          - arm_l_joint4
          - arm_l_joint5
          - arm_l_joint6
          - arm_l_joint7
          - l_rh_r1_joint
        leader_left:
          - arm_l_joint1
          - arm_l_joint2
          - arm_l_joint3
          - arm_l_joint4
          - arm_l_joint5
          - arm_l_joint6
          - arm_l_joint7
          - l_rh_r1_joint
        leader_right:
          - arm_r_joint1
          - arm_r_joint2
          - arm_r_joint3
          - arm_r_joint4
          - arm_r_joint5
          - arm_r_joint6
          - arm_r_joint7
          - r_rh_r1_joint

    ai_worker_with_inspire:
      camera_topic_list:
        - "head_image_topic_name:/realSense/Color/image_raw/compressed"

      joint_sub_topic_list:
        - "follower_joint_sub:/ai_worker/follower/joint_states"
        - "leader_left_joint_sub:/ai_worker/leader/left_joint_states"
        - "leader_right_joint_sub:/ai_worker/leader/right_joint_states"
      
      joint_pub_topic_list:
        - "follower_joint_pub:/ai_worker/follower/joint_position_controller/commands"

      observation_list:
        - "state"
        - "cam_head"
        - "cam_wrist_left"
        - "cam_wrist_right"

      joint_list:
        - "follower"
        - "leader_right_hand"
        - "leader_left_hand"
        - "leader_right_arm"
        - "leader_left_arm" 

      inference_joint_order:
        follower:
          - arm_r_joint1
          - arm_r_joint2
          - arm_r_joint3
          - arm_r_joint4
          - arm_r_joint5
          - arm_r_joint6
          - arm_r_joint7
          - arm_l_joint1
          - arm_l_joint2
          - arm_l_joint3
          - arm_l_joint4
          - arm_l_joint5
          - arm_l_joint6
          - arm_l_joint7
        leader_right_hand:
          - right_little_1_joint
          - right_ring_1_joint
          - right_middle_1_joint
          - right_index_1_joint
          - right_thumb_2_joint
          - right_thumb_1_joint
        leader_left_hand:
          - left_little_1_joint
          - left_ring_1_joint
          - left_middle_1_joint
          - left_index_1_joint
          - left_thumb_2_joint
          - left_thumb_1_joint
        leader_right_arm:
          - arm_r_joint1
          - arm_r_joint2
          - arm_r_joint3
          - arm_r_joint4
          - arm_r_joint5
          - arm_r_joint6
          - arm_r_joint7
        leader_left_arm:
          - arm_l_joint1
          - arm_l_joint2
          - arm_l_joint3
          - arm_l_joint4
          - arm_l_joint5
          - arm_l_joint6
          - arm_l_joint7

      collect_joint_order:
        follower:
          - arm_r_joint1
          - arm_r_joint2
          - arm_r_joint3
          - arm_r_joint4
          - arm_r_joint5
          - arm_r_joint6
          - arm_r_joint7
          - arm_l_joint1
          - arm_l_joint2
          - arm_l_joint3
          - arm_l_joint4
          - arm_l_joint5
          - arm_l_joint6
          - arm_l_joint7
        leader_right_hand:
          - right_little_1_joint
          - right_ring_1_joint
          - right_middle_1_joint
          - right_index_1_joint
          - right_thumb_2_joint
          - right_thumb_1_joint
        leader_left_hand:
          - left_little_1_joint
          - left_ring_1_joint
          - left_middle_1_joint
          - left_index_1_joint
          - left_thumb_2_joint
          - left_thumb_1_joint
        leader_right_arm:
          - arm_r_joint1
          - arm_r_joint2
          - arm_r_joint3
          - arm_r_joint4
          - arm_r_joint5
          - arm_r_joint6
          - arm_r_joint7
        leader_left_arm:
          - arm_l_joint1
          - arm_l_joint2
          - arm_l_joint3
          - arm_l_joint4
          - arm_l_joint5
          - arm_l_joint6
          - arm_l_joint7

    om_x:
      camera_topic_list:
        - "wrist_image_topic_name:/realSense/Color/image_raw/compressed"

      joint_sub_topic_list:
        - "follower_joint_sub:/follower/joint_states"
        - "leader_joint_sub:/leader/left_arm_with_timestamp"
      
      joint_pub_topic_list:
        - "follower_joint_pub:/follower/joint_position_controller/commands"

      observation_list:
        - "state"
        - "cam_wrist"

      joint_list:
        - "follower"
        - "leader"

      inference_joint_order:
        follower:
          - joint1
          - joint2
          - joint3
          - joint4
          - gripper
        leader:
          - joint1
          - joint2
          - joint3
          - joint4
          - gripper

      collect_joint_order:
        follower:
          - joint1
          - joint2
          - joint3
          - joint4
          - gripper
        leader:
          - joint1
          - joint2
          - joint3
          - joint4
          - gripper

    om_y:
      camera_topic_list:
        - "cam_wrist:/realSense/Color/image_raw/compressed"

      joint_sub_topic_list:
        - "follower_state:/follower/joint_states"
        - "leader_joint:/leader/left_arm_with_timestamp"

      joint_pub_topic_list:
        - "follower_joint_pub:/follower/joint_position_controller/commands"

      observation_list:
        - "state"
        - "cam_wrist"

      joint_list:
        - "follower"
        - "leader"

      inference_joint_order:
        follower:
          - joint1
          - joint2
          - joint3
          - joint4
          - joint5
          - joint6
          - gripper
        leader:
          - joint1
          - joint2
          - joint3
          - joint4
          - joint5
          - joint6
          - gripper

      collect_joint_order:
        follower:
          - joint1
          - joint2
          - joint3
          - joint4
          - joint5
          - joint6
          - gripper
        leader:
          - joint1
          - joint2
          - joint3
          - joint4
          - joint5
          - joint6
          - gripper
        
