physical_ai_server:
  ros__parameters:
    ai_worker_with_inspired:
      observation_list:
        - state
        - cam_head

      camera_topic_list:
        - cam_head:/camera_head/camera_head/color/image_rect_raw/compressed

      joint_topic_list:
        - follower:/joint_states
        - leader_left:/leader/joint_trajectory_command_broadcaster_left/joint_trajectory
        - leader_right:/leader/joint_trajectory_command_broadcaster_right/joint_trajectory
        - leader_left_hand:/leader/left_hand_with_timestamp
        - leader_right_hand:/leader/right_hand_with_timestamp
        - leader_head:/leader/joystick_controller_left/joint_trajectory
        - leader_lift:/leader/joystick_controller_right/joint_trajectory

      joint_list:
        - leader_right_arm
        - leader_left_arm 
        - leader_right_hand
        - leader_left_hand
        - leader_head
        - leader_lift

      joint_order:
        leader_right_arm:
          - arm_r_joint1
          - arm_r_joint2
          - arm_r_joint3
          - arm_r_joint4
          - arm_r_joint5
          - arm_r_joint6
          - arm_r_joint7
        leader_left_arm:
          - arm_l_joint1
          - arm_l_joint2
          - arm_l_joint3
          - arm_l_joint4
          - arm_l_joint5
          - arm_l_joint6
          - arm_l_joint7
        leader_right_hand:
          - right_little_1_joint
          - right_ring_1_joint
          - right_middle_1_joint
          - right_index_1_joint
          - right_thumb_2_joint
          - right_thumb_1_joint
        leader_left_hand:
          - left_little_1_joint
          - left_ring_1_joint
          - left_middle_1_joint
          - left_index_1_joint
          - left_thumb_2_joint
          - left_thumb_1_joint
        leader_head:
          - head_joint1
          - head_joint2
        leader_lift:
          - lift_joint
