physical_ai_server:
  ros__parameters:
    gaemi:
      observation_list:
        - front_f_view
        - front_l_view
        - front_r_view
        - state

      camera_topic_list: 
        - front_f_view:/sensor/camera/realsense/front_view/front/color/image_raw/compressed
        - front_l_view:/sensor/camera/realsense/front_view/left/color/image_raw/compressed
        - front_r_view:/sensor/camera/realsense/front_view/right/color/image_raw/compressed

      joint_topic_list:
        - follower_mobile:/slam/localization/odom
        - leader_mobile:/pilot/cmd_vel

      joint_list:
        - leader_mobile

      joint_order:
        leader_mobile:
          - linear_x
          - angular_z
