physical_ai_server:
  ros__parameters:
    omx:
      observation_list:
        - cam_global
        - state

      camera_topic_list:
        - cam_global:/camera1/image_raw/compressed

      joint_topic_list:
        - follower:/joint_states
        - leader:/leader/joint_trajectory

      joint_list:
        - leader

      joint_order:
        leader:
          - joint1
          - joint2
          - joint3
          - joint4
          - joint5
          - joint6
