physical_ai_server:
  ros__parameters:
    omy_f3m:
      observation_list:
        - cam_wrist
        - state

      camera_topic_list:
        - cam_wrist:/camera/cam_wrist/color/image_rect_raw/compressed

      joint_topic_list:
        - follower:/joint_states
        - leader:/leader/joint_trajectory

      joint_list:
        - leader

      joint_order:
        leader:
          - joint1
          - joint2
          - joint3
          - joint4
          - joint5
          - joint6
          - rh_r1_joint
